// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ida/worker/v1/service.proto

package workerconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/zboralski/ida-headless-mcp/ida/worker/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionControlName is the fully-qualified name of the SessionControl service.
	SessionControlName = "ida.worker.v1.SessionControl"
	// AnalysisToolsName is the fully-qualified name of the AnalysisTools service.
	AnalysisToolsName = "ida.worker.v1.AnalysisTools"
	// HealthcheckName is the fully-qualified name of the Healthcheck service.
	HealthcheckName = "ida.worker.v1.Healthcheck"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionControlOpenBinaryProcedure is the fully-qualified name of the SessionControl's OpenBinary
	// RPC.
	SessionControlOpenBinaryProcedure = "/ida.worker.v1.SessionControl/OpenBinary"
	// SessionControlCloseSessionProcedure is the fully-qualified name of the SessionControl's
	// CloseSession RPC.
	SessionControlCloseSessionProcedure = "/ida.worker.v1.SessionControl/CloseSession"
	// SessionControlSaveDatabaseProcedure is the fully-qualified name of the SessionControl's
	// SaveDatabase RPC.
	SessionControlSaveDatabaseProcedure = "/ida.worker.v1.SessionControl/SaveDatabase"
	// SessionControlPlanAndWaitProcedure is the fully-qualified name of the SessionControl's
	// PlanAndWait RPC.
	SessionControlPlanAndWaitProcedure = "/ida.worker.v1.SessionControl/PlanAndWait"
	// SessionControlGetSessionInfoProcedure is the fully-qualified name of the SessionControl's
	// GetSessionInfo RPC.
	SessionControlGetSessionInfoProcedure = "/ida.worker.v1.SessionControl/GetSessionInfo"
	// AnalysisToolsGetBytesProcedure is the fully-qualified name of the AnalysisTools's GetBytes RPC.
	AnalysisToolsGetBytesProcedure = "/ida.worker.v1.AnalysisTools/GetBytes"
	// AnalysisToolsGetDisasmProcedure is the fully-qualified name of the AnalysisTools's GetDisasm RPC.
	AnalysisToolsGetDisasmProcedure = "/ida.worker.v1.AnalysisTools/GetDisasm"
	// AnalysisToolsGetFunctionDisasmProcedure is the fully-qualified name of the AnalysisTools's
	// GetFunctionDisasm RPC.
	AnalysisToolsGetFunctionDisasmProcedure = "/ida.worker.v1.AnalysisTools/GetFunctionDisasm"
	// AnalysisToolsGetDecompiledProcedure is the fully-qualified name of the AnalysisTools's
	// GetDecompiled RPC.
	AnalysisToolsGetDecompiledProcedure = "/ida.worker.v1.AnalysisTools/GetDecompiled"
	// AnalysisToolsGetFunctionNameProcedure is the fully-qualified name of the AnalysisTools's
	// GetFunctionName RPC.
	AnalysisToolsGetFunctionNameProcedure = "/ida.worker.v1.AnalysisTools/GetFunctionName"
	// AnalysisToolsGetSegmentsProcedure is the fully-qualified name of the AnalysisTools's GetSegments
	// RPC.
	AnalysisToolsGetSegmentsProcedure = "/ida.worker.v1.AnalysisTools/GetSegments"
	// AnalysisToolsGetFunctionsProcedure is the fully-qualified name of the AnalysisTools's
	// GetFunctions RPC.
	AnalysisToolsGetFunctionsProcedure = "/ida.worker.v1.AnalysisTools/GetFunctions"
	// AnalysisToolsGetXRefsToProcedure is the fully-qualified name of the AnalysisTools's GetXRefsTo
	// RPC.
	AnalysisToolsGetXRefsToProcedure = "/ida.worker.v1.AnalysisTools/GetXRefsTo"
	// AnalysisToolsGetXRefsFromProcedure is the fully-qualified name of the AnalysisTools's
	// GetXRefsFrom RPC.
	AnalysisToolsGetXRefsFromProcedure = "/ida.worker.v1.AnalysisTools/GetXRefsFrom"
	// AnalysisToolsGetDataRefsProcedure is the fully-qualified name of the AnalysisTools's GetDataRefs
	// RPC.
	AnalysisToolsGetDataRefsProcedure = "/ida.worker.v1.AnalysisTools/GetDataRefs"
	// AnalysisToolsGetStringXRefsProcedure is the fully-qualified name of the AnalysisTools's
	// GetStringXRefs RPC.
	AnalysisToolsGetStringXRefsProcedure = "/ida.worker.v1.AnalysisTools/GetStringXRefs"
	// AnalysisToolsGetImportsProcedure is the fully-qualified name of the AnalysisTools's GetImports
	// RPC.
	AnalysisToolsGetImportsProcedure = "/ida.worker.v1.AnalysisTools/GetImports"
	// AnalysisToolsGetExportsProcedure is the fully-qualified name of the AnalysisTools's GetExports
	// RPC.
	AnalysisToolsGetExportsProcedure = "/ida.worker.v1.AnalysisTools/GetExports"
	// AnalysisToolsGetEntryPointProcedure is the fully-qualified name of the AnalysisTools's
	// GetEntryPoint RPC.
	AnalysisToolsGetEntryPointProcedure = "/ida.worker.v1.AnalysisTools/GetEntryPoint"
	// AnalysisToolsGetStringsProcedure is the fully-qualified name of the AnalysisTools's GetStrings
	// RPC.
	AnalysisToolsGetStringsProcedure = "/ida.worker.v1.AnalysisTools/GetStrings"
	// AnalysisToolsMakeFunctionProcedure is the fully-qualified name of the AnalysisTools's
	// MakeFunction RPC.
	AnalysisToolsMakeFunctionProcedure = "/ida.worker.v1.AnalysisTools/MakeFunction"
	// AnalysisToolsImportIl2CppProcedure is the fully-qualified name of the AnalysisTools's
	// ImportIl2Cpp RPC.
	AnalysisToolsImportIl2CppProcedure = "/ida.worker.v1.AnalysisTools/ImportIl2Cpp"
	// AnalysisToolsImportFlutterProcedure is the fully-qualified name of the AnalysisTools's
	// ImportFlutter RPC.
	AnalysisToolsImportFlutterProcedure = "/ida.worker.v1.AnalysisTools/ImportFlutter"
	// AnalysisToolsGetGlobalsProcedure is the fully-qualified name of the AnalysisTools's GetGlobals
	// RPC.
	AnalysisToolsGetGlobalsProcedure = "/ida.worker.v1.AnalysisTools/GetGlobals"
	// AnalysisToolsSetGlobalTypeProcedure is the fully-qualified name of the AnalysisTools's
	// SetGlobalType RPC.
	AnalysisToolsSetGlobalTypeProcedure = "/ida.worker.v1.AnalysisTools/SetGlobalType"
	// AnalysisToolsRenameGlobalProcedure is the fully-qualified name of the AnalysisTools's
	// RenameGlobal RPC.
	AnalysisToolsRenameGlobalProcedure = "/ida.worker.v1.AnalysisTools/RenameGlobal"
	// AnalysisToolsDataReadStringProcedure is the fully-qualified name of the AnalysisTools's
	// DataReadString RPC.
	AnalysisToolsDataReadStringProcedure = "/ida.worker.v1.AnalysisTools/DataReadString"
	// AnalysisToolsDataReadByteProcedure is the fully-qualified name of the AnalysisTools's
	// DataReadByte RPC.
	AnalysisToolsDataReadByteProcedure = "/ida.worker.v1.AnalysisTools/DataReadByte"
	// AnalysisToolsFindBinaryProcedure is the fully-qualified name of the AnalysisTools's FindBinary
	// RPC.
	AnalysisToolsFindBinaryProcedure = "/ida.worker.v1.AnalysisTools/FindBinary"
	// AnalysisToolsFindTextProcedure is the fully-qualified name of the AnalysisTools's FindText RPC.
	AnalysisToolsFindTextProcedure = "/ida.worker.v1.AnalysisTools/FindText"
	// AnalysisToolsListStructsProcedure is the fully-qualified name of the AnalysisTools's ListStructs
	// RPC.
	AnalysisToolsListStructsProcedure = "/ida.worker.v1.AnalysisTools/ListStructs"
	// AnalysisToolsGetStructProcedure is the fully-qualified name of the AnalysisTools's GetStruct RPC.
	AnalysisToolsGetStructProcedure = "/ida.worker.v1.AnalysisTools/GetStruct"
	// AnalysisToolsListEnumsProcedure is the fully-qualified name of the AnalysisTools's ListEnums RPC.
	AnalysisToolsListEnumsProcedure = "/ida.worker.v1.AnalysisTools/ListEnums"
	// AnalysisToolsGetEnumProcedure is the fully-qualified name of the AnalysisTools's GetEnum RPC.
	AnalysisToolsGetEnumProcedure = "/ida.worker.v1.AnalysisTools/GetEnum"
	// AnalysisToolsGetFunctionInfoProcedure is the fully-qualified name of the AnalysisTools's
	// GetFunctionInfo RPC.
	AnalysisToolsGetFunctionInfoProcedure = "/ida.worker.v1.AnalysisTools/GetFunctionInfo"
	// AnalysisToolsGetTypeAtProcedure is the fully-qualified name of the AnalysisTools's GetTypeAt RPC.
	AnalysisToolsGetTypeAtProcedure = "/ida.worker.v1.AnalysisTools/GetTypeAt"
	// AnalysisToolsGetDwordAtProcedure is the fully-qualified name of the AnalysisTools's GetDwordAt
	// RPC.
	AnalysisToolsGetDwordAtProcedure = "/ida.worker.v1.AnalysisTools/GetDwordAt"
	// AnalysisToolsGetQwordAtProcedure is the fully-qualified name of the AnalysisTools's GetQwordAt
	// RPC.
	AnalysisToolsGetQwordAtProcedure = "/ida.worker.v1.AnalysisTools/GetQwordAt"
	// AnalysisToolsGetInstructionLengthProcedure is the fully-qualified name of the AnalysisTools's
	// GetInstructionLength RPC.
	AnalysisToolsGetInstructionLengthProcedure = "/ida.worker.v1.AnalysisTools/GetInstructionLength"
	// AnalysisToolsSetCommentProcedure is the fully-qualified name of the AnalysisTools's SetComment
	// RPC.
	AnalysisToolsSetCommentProcedure = "/ida.worker.v1.AnalysisTools/SetComment"
	// AnalysisToolsGetCommentProcedure is the fully-qualified name of the AnalysisTools's GetComment
	// RPC.
	AnalysisToolsGetCommentProcedure = "/ida.worker.v1.AnalysisTools/GetComment"
	// AnalysisToolsSetFuncCommentProcedure is the fully-qualified name of the AnalysisTools's
	// SetFuncComment RPC.
	AnalysisToolsSetFuncCommentProcedure = "/ida.worker.v1.AnalysisTools/SetFuncComment"
	// AnalysisToolsGetFuncCommentProcedure is the fully-qualified name of the AnalysisTools's
	// GetFuncComment RPC.
	AnalysisToolsGetFuncCommentProcedure = "/ida.worker.v1.AnalysisTools/GetFuncComment"
	// AnalysisToolsSetLvarTypeProcedure is the fully-qualified name of the AnalysisTools's SetLvarType
	// RPC.
	AnalysisToolsSetLvarTypeProcedure = "/ida.worker.v1.AnalysisTools/SetLvarType"
	// AnalysisToolsRenameLvarProcedure is the fully-qualified name of the AnalysisTools's RenameLvar
	// RPC.
	AnalysisToolsRenameLvarProcedure = "/ida.worker.v1.AnalysisTools/RenameLvar"
	// AnalysisToolsSetDecompilerCommentProcedure is the fully-qualified name of the AnalysisTools's
	// SetDecompilerComment RPC.
	AnalysisToolsSetDecompilerCommentProcedure = "/ida.worker.v1.AnalysisTools/SetDecompilerComment"
	// AnalysisToolsSetNameProcedure is the fully-qualified name of the AnalysisTools's SetName RPC.
	AnalysisToolsSetNameProcedure = "/ida.worker.v1.AnalysisTools/SetName"
	// AnalysisToolsGetNameProcedure is the fully-qualified name of the AnalysisTools's GetName RPC.
	AnalysisToolsGetNameProcedure = "/ida.worker.v1.AnalysisTools/GetName"
	// AnalysisToolsDeleteNameProcedure is the fully-qualified name of the AnalysisTools's DeleteName
	// RPC.
	AnalysisToolsDeleteNameProcedure = "/ida.worker.v1.AnalysisTools/DeleteName"
	// AnalysisToolsSetFunctionTypeProcedure is the fully-qualified name of the AnalysisTools's
	// SetFunctionType RPC.
	AnalysisToolsSetFunctionTypeProcedure = "/ida.worker.v1.AnalysisTools/SetFunctionType"
	// HealthcheckPingProcedure is the fully-qualified name of the Healthcheck's Ping RPC.
	HealthcheckPingProcedure = "/ida.worker.v1.Healthcheck/Ping"
	// HealthcheckStatusStreamProcedure is the fully-qualified name of the Healthcheck's StatusStream
	// RPC.
	HealthcheckStatusStreamProcedure = "/ida.worker.v1.Healthcheck/StatusStream"
)

// SessionControlClient is a client for the ida.worker.v1.SessionControl service.
type SessionControlClient interface {
	// OpenBinary opens a binary file for analysis
	OpenBinary(context.Context, *connect.Request[v1.OpenBinaryRequest]) (*connect.Response[v1.OpenBinaryResponse], error)
	// CloseSession closes the database and terminates analysis
	CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error)
	// SaveDatabase saves the current database state
	SaveDatabase(context.Context, *connect.Request[v1.SaveDatabaseRequest]) (*connect.Response[v1.SaveDatabaseResponse], error)
	// PlanAndWait forces IDA auto-analysis to complete outstanding work
	PlanAndWait(context.Context, *connect.Request[v1.PlanAndWaitRequest]) (*connect.Response[v1.PlanAndWaitResponse], error)
	// GetSessionInfo returns current session metadata
	GetSessionInfo(context.Context, *connect.Request[v1.GetSessionInfoRequest]) (*connect.Response[v1.GetSessionInfoResponse], error)
}

// NewSessionControlClient constructs a client for the ida.worker.v1.SessionControl service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionControlClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionControlClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionControlMethods := v1.File_ida_worker_v1_service_proto.Services().ByName("SessionControl").Methods()
	return &sessionControlClient{
		openBinary: connect.NewClient[v1.OpenBinaryRequest, v1.OpenBinaryResponse](
			httpClient,
			baseURL+SessionControlOpenBinaryProcedure,
			connect.WithSchema(sessionControlMethods.ByName("OpenBinary")),
			connect.WithClientOptions(opts...),
		),
		closeSession: connect.NewClient[v1.CloseSessionRequest, v1.CloseSessionResponse](
			httpClient,
			baseURL+SessionControlCloseSessionProcedure,
			connect.WithSchema(sessionControlMethods.ByName("CloseSession")),
			connect.WithClientOptions(opts...),
		),
		saveDatabase: connect.NewClient[v1.SaveDatabaseRequest, v1.SaveDatabaseResponse](
			httpClient,
			baseURL+SessionControlSaveDatabaseProcedure,
			connect.WithSchema(sessionControlMethods.ByName("SaveDatabase")),
			connect.WithClientOptions(opts...),
		),
		planAndWait: connect.NewClient[v1.PlanAndWaitRequest, v1.PlanAndWaitResponse](
			httpClient,
			baseURL+SessionControlPlanAndWaitProcedure,
			connect.WithSchema(sessionControlMethods.ByName("PlanAndWait")),
			connect.WithClientOptions(opts...),
		),
		getSessionInfo: connect.NewClient[v1.GetSessionInfoRequest, v1.GetSessionInfoResponse](
			httpClient,
			baseURL+SessionControlGetSessionInfoProcedure,
			connect.WithSchema(sessionControlMethods.ByName("GetSessionInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionControlClient implements SessionControlClient.
type sessionControlClient struct {
	openBinary     *connect.Client[v1.OpenBinaryRequest, v1.OpenBinaryResponse]
	closeSession   *connect.Client[v1.CloseSessionRequest, v1.CloseSessionResponse]
	saveDatabase   *connect.Client[v1.SaveDatabaseRequest, v1.SaveDatabaseResponse]
	planAndWait    *connect.Client[v1.PlanAndWaitRequest, v1.PlanAndWaitResponse]
	getSessionInfo *connect.Client[v1.GetSessionInfoRequest, v1.GetSessionInfoResponse]
}

// OpenBinary calls ida.worker.v1.SessionControl.OpenBinary.
func (c *sessionControlClient) OpenBinary(ctx context.Context, req *connect.Request[v1.OpenBinaryRequest]) (*connect.Response[v1.OpenBinaryResponse], error) {
	return c.openBinary.CallUnary(ctx, req)
}

// CloseSession calls ida.worker.v1.SessionControl.CloseSession.
func (c *sessionControlClient) CloseSession(ctx context.Context, req *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error) {
	return c.closeSession.CallUnary(ctx, req)
}

// SaveDatabase calls ida.worker.v1.SessionControl.SaveDatabase.
func (c *sessionControlClient) SaveDatabase(ctx context.Context, req *connect.Request[v1.SaveDatabaseRequest]) (*connect.Response[v1.SaveDatabaseResponse], error) {
	return c.saveDatabase.CallUnary(ctx, req)
}

// PlanAndWait calls ida.worker.v1.SessionControl.PlanAndWait.
func (c *sessionControlClient) PlanAndWait(ctx context.Context, req *connect.Request[v1.PlanAndWaitRequest]) (*connect.Response[v1.PlanAndWaitResponse], error) {
	return c.planAndWait.CallUnary(ctx, req)
}

// GetSessionInfo calls ida.worker.v1.SessionControl.GetSessionInfo.
func (c *sessionControlClient) GetSessionInfo(ctx context.Context, req *connect.Request[v1.GetSessionInfoRequest]) (*connect.Response[v1.GetSessionInfoResponse], error) {
	return c.getSessionInfo.CallUnary(ctx, req)
}

// SessionControlHandler is an implementation of the ida.worker.v1.SessionControl service.
type SessionControlHandler interface {
	// OpenBinary opens a binary file for analysis
	OpenBinary(context.Context, *connect.Request[v1.OpenBinaryRequest]) (*connect.Response[v1.OpenBinaryResponse], error)
	// CloseSession closes the database and terminates analysis
	CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error)
	// SaveDatabase saves the current database state
	SaveDatabase(context.Context, *connect.Request[v1.SaveDatabaseRequest]) (*connect.Response[v1.SaveDatabaseResponse], error)
	// PlanAndWait forces IDA auto-analysis to complete outstanding work
	PlanAndWait(context.Context, *connect.Request[v1.PlanAndWaitRequest]) (*connect.Response[v1.PlanAndWaitResponse], error)
	// GetSessionInfo returns current session metadata
	GetSessionInfo(context.Context, *connect.Request[v1.GetSessionInfoRequest]) (*connect.Response[v1.GetSessionInfoResponse], error)
}

// NewSessionControlHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionControlHandler(svc SessionControlHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionControlMethods := v1.File_ida_worker_v1_service_proto.Services().ByName("SessionControl").Methods()
	sessionControlOpenBinaryHandler := connect.NewUnaryHandler(
		SessionControlOpenBinaryProcedure,
		svc.OpenBinary,
		connect.WithSchema(sessionControlMethods.ByName("OpenBinary")),
		connect.WithHandlerOptions(opts...),
	)
	sessionControlCloseSessionHandler := connect.NewUnaryHandler(
		SessionControlCloseSessionProcedure,
		svc.CloseSession,
		connect.WithSchema(sessionControlMethods.ByName("CloseSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionControlSaveDatabaseHandler := connect.NewUnaryHandler(
		SessionControlSaveDatabaseProcedure,
		svc.SaveDatabase,
		connect.WithSchema(sessionControlMethods.ByName("SaveDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	sessionControlPlanAndWaitHandler := connect.NewUnaryHandler(
		SessionControlPlanAndWaitProcedure,
		svc.PlanAndWait,
		connect.WithSchema(sessionControlMethods.ByName("PlanAndWait")),
		connect.WithHandlerOptions(opts...),
	)
	sessionControlGetSessionInfoHandler := connect.NewUnaryHandler(
		SessionControlGetSessionInfoProcedure,
		svc.GetSessionInfo,
		connect.WithSchema(sessionControlMethods.ByName("GetSessionInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ida.worker.v1.SessionControl/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionControlOpenBinaryProcedure:
			sessionControlOpenBinaryHandler.ServeHTTP(w, r)
		case SessionControlCloseSessionProcedure:
			sessionControlCloseSessionHandler.ServeHTTP(w, r)
		case SessionControlSaveDatabaseProcedure:
			sessionControlSaveDatabaseHandler.ServeHTTP(w, r)
		case SessionControlPlanAndWaitProcedure:
			sessionControlPlanAndWaitHandler.ServeHTTP(w, r)
		case SessionControlGetSessionInfoProcedure:
			sessionControlGetSessionInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionControlHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionControlHandler struct{}

func (UnimplementedSessionControlHandler) OpenBinary(context.Context, *connect.Request[v1.OpenBinaryRequest]) (*connect.Response[v1.OpenBinaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.SessionControl.OpenBinary is not implemented"))
}

func (UnimplementedSessionControlHandler) CloseSession(context.Context, *connect.Request[v1.CloseSessionRequest]) (*connect.Response[v1.CloseSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.SessionControl.CloseSession is not implemented"))
}

func (UnimplementedSessionControlHandler) SaveDatabase(context.Context, *connect.Request[v1.SaveDatabaseRequest]) (*connect.Response[v1.SaveDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.SessionControl.SaveDatabase is not implemented"))
}

func (UnimplementedSessionControlHandler) PlanAndWait(context.Context, *connect.Request[v1.PlanAndWaitRequest]) (*connect.Response[v1.PlanAndWaitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.SessionControl.PlanAndWait is not implemented"))
}

func (UnimplementedSessionControlHandler) GetSessionInfo(context.Context, *connect.Request[v1.GetSessionInfoRequest]) (*connect.Response[v1.GetSessionInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.SessionControl.GetSessionInfo is not implemented"))
}

// AnalysisToolsClient is a client for the ida.worker.v1.AnalysisTools service.
type AnalysisToolsClient interface {
	// GetBytes reads raw bytes from address
	GetBytes(context.Context, *connect.Request[v1.GetBytesRequest]) (*connect.Response[v1.GetBytesResponse], error)
	// GetDisasm returns disassembly at address
	GetDisasm(context.Context, *connect.Request[v1.GetDisasmRequest]) (*connect.Response[v1.GetDisasmResponse], error)
	// GetFunctionDisasm returns full disassembly for a function
	GetFunctionDisasm(context.Context, *connect.Request[v1.GetFunctionDisasmRequest]) (*connect.Response[v1.GetFunctionDisasmResponse], error)
	// GetDecompiled returns decompiled pseudocode
	GetDecompiled(context.Context, *connect.Request[v1.GetDecompiledRequest]) (*connect.Response[v1.GetDecompiledResponse], error)
	// GetFunctionName returns function name at address
	GetFunctionName(context.Context, *connect.Request[v1.GetFunctionNameRequest]) (*connect.Response[v1.GetFunctionNameResponse], error)
	// GetSegments returns all memory segments
	GetSegments(context.Context, *connect.Request[v1.GetSegmentsRequest]) (*connect.Response[v1.GetSegmentsResponse], error)
	// GetFunctions returns all functions
	GetFunctions(context.Context, *connect.Request[v1.GetFunctionsRequest]) (*connect.Response[v1.GetFunctionsResponse], error)
	// GetXRefsTo returns cross-references to address
	GetXRefsTo(context.Context, *connect.Request[v1.GetXRefsToRequest]) (*connect.Response[v1.GetXRefsToResponse], error)
	// GetXRefsFrom returns outgoing references from address
	GetXRefsFrom(context.Context, *connect.Request[v1.GetXRefsFromRequest]) (*connect.Response[v1.GetXRefsFromResponse], error)
	// GetDataRefs returns data references to address
	GetDataRefs(context.Context, *connect.Request[v1.GetDataRefsRequest]) (*connect.Response[v1.GetDataRefsResponse], error)
	// GetStringXRefs returns string references for address
	GetStringXRefs(context.Context, *connect.Request[v1.GetStringXRefsRequest]) (*connect.Response[v1.GetStringXRefsResponse], error)
	// GetImports returns import table
	GetImports(context.Context, *connect.Request[v1.GetImportsRequest]) (*connect.Response[v1.GetImportsResponse], error)
	// GetExports returns export table
	GetExports(context.Context, *connect.Request[v1.GetExportsRequest]) (*connect.Response[v1.GetExportsResponse], error)
	// GetEntryPoint returns binary entry point
	GetEntryPoint(context.Context, *connect.Request[v1.GetEntryPointRequest]) (*connect.Response[v1.GetEntryPointResponse], error)
	// GetStrings returns all strings in binary
	GetStrings(context.Context, *connect.Request[v1.GetStringsRequest]) (*connect.Response[v1.GetStringsResponse], error)
	// MakeFunction creates function at address
	MakeFunction(context.Context, *connect.Request[v1.MakeFunctionRequest]) (*connect.Response[v1.MakeFunctionResponse], error)
	// ImportIl2Cpp ingests Il2CppDumper metadata into the current database
	ImportIl2Cpp(context.Context, *connect.Request[v1.ImportIl2CppRequest]) (*connect.Response[v1.ImportIl2CppResponse], error)
	// ImportFlutter ingests Blutter output into the current database
	ImportFlutter(context.Context, *connect.Request[v1.ImportFlutterRequest]) (*connect.Response[v1.ImportFlutterResponse], error)
	// GetGlobals enumerates global variables
	GetGlobals(context.Context, *connect.Request[v1.GetGlobalsRequest]) (*connect.Response[v1.GetGlobalsResponse], error)
	// SetGlobalType sets the type of a global variable
	SetGlobalType(context.Context, *connect.Request[v1.SetGlobalTypeRequest]) (*connect.Response[v1.SetGlobalTypeResponse], error)
	// RenameGlobal renames a global variable
	RenameGlobal(context.Context, *connect.Request[v1.RenameGlobalRequest]) (*connect.Response[v1.RenameGlobalResponse], error)
	// DataReadString reads an ASCII/UTF-8 string from memory
	DataReadString(context.Context, *connect.Request[v1.DataReadStringRequest]) (*connect.Response[v1.DataReadStringResponse], error)
	// DataReadByte reads a single byte from memory
	DataReadByte(context.Context, *connect.Request[v1.DataReadByteRequest]) (*connect.Response[v1.DataReadByteResponse], error)
	// FindBinary searches for byte patterns
	FindBinary(context.Context, *connect.Request[v1.FindBinaryRequest]) (*connect.Response[v1.FindBinaryResponse], error)
	// FindText searches for ASCII/UTF-8 strings
	FindText(context.Context, *connect.Request[v1.FindTextRequest]) (*connect.Response[v1.FindTextResponse], error)
	// ListStructs enumerates structure definitions
	ListStructs(context.Context, *connect.Request[v1.ListStructsRequest]) (*connect.Response[v1.ListStructsResponse], error)
	// GetStruct returns metadata for a specific structure
	GetStruct(context.Context, *connect.Request[v1.GetStructRequest]) (*connect.Response[v1.GetStructResponse], error)
	// ListEnums enumerates all enumerations with optional filtering
	ListEnums(context.Context, *connect.Request[v1.ListEnumsRequest]) (*connect.Response[v1.ListEnumsResponse], error)
	// GetEnum returns metadata for a specific enumeration
	GetEnum(context.Context, *connect.Request[v1.GetEnumRequest]) (*connect.Response[v1.GetEnumResponse], error)
	// GetFunctionInfo returns comprehensive function metadata
	GetFunctionInfo(context.Context, *connect.Request[v1.GetFunctionInfoRequest]) (*connect.Response[v1.GetFunctionInfoResponse], error)
	// GetTypeAt returns type information at address
	GetTypeAt(context.Context, *connect.Request[v1.GetTypeAtRequest]) (*connect.Response[v1.GetTypeAtResponse], error)
	// GetDwordAt reads 32-bit value
	GetDwordAt(context.Context, *connect.Request[v1.GetDwordAtRequest]) (*connect.Response[v1.GetDwordAtResponse], error)
	// GetQwordAt reads 64-bit value
	GetQwordAt(context.Context, *connect.Request[v1.GetQwordAtRequest]) (*connect.Response[v1.GetQwordAtResponse], error)
	// GetInstructionLength returns instruction size
	GetInstructionLength(context.Context, *connect.Request[v1.GetInstructionLengthRequest]) (*connect.Response[v1.GetInstructionLengthResponse], error)
	// SetComment sets comment at address
	SetComment(context.Context, *connect.Request[v1.SetCommentRequest]) (*connect.Response[v1.SetCommentResponse], error)
	// GetComment returns comment at address
	GetComment(context.Context, *connect.Request[v1.GetCommentRequest]) (*connect.Response[v1.GetCommentResponse], error)
	// SetFuncComment sets function comment
	SetFuncComment(context.Context, *connect.Request[v1.SetFuncCommentRequest]) (*connect.Response[v1.SetFuncCommentResponse], error)
	// GetFuncComment returns function comment
	GetFuncComment(context.Context, *connect.Request[v1.GetFuncCommentRequest]) (*connect.Response[v1.GetFuncCommentResponse], error)
	// SetLvarType sets Hex-Rays local variable type
	SetLvarType(context.Context, *connect.Request[v1.SetLvarTypeRequest]) (*connect.Response[v1.SetLvarTypeResponse], error)
	// RenameLvar renames a Hex-Rays local variable
	RenameLvar(context.Context, *connect.Request[v1.RenameLvarRequest]) (*connect.Response[v1.RenameLvarResponse], error)
	// SetDecompilerComment sets a Hex-Rays pseudocode comment
	SetDecompilerComment(context.Context, *connect.Request[v1.SetDecompilerCommentRequest]) (*connect.Response[v1.SetDecompilerCommentResponse], error)
	// SetName sets name at address
	SetName(context.Context, *connect.Request[v1.SetNameRequest]) (*connect.Response[v1.SetNameResponse], error)
	// GetName returns name at address
	GetName(context.Context, *connect.Request[v1.GetNameRequest]) (*connect.Response[v1.GetNameResponse], error)
	// DeleteName removes name at address
	DeleteName(context.Context, *connect.Request[v1.DeleteNameRequest]) (*connect.Response[v1.DeleteNameResponse], error)
	// SetFunctionType applies a C-style prototype to a function
	SetFunctionType(context.Context, *connect.Request[v1.SetFunctionTypeRequest]) (*connect.Response[v1.SetFunctionTypeResponse], error)
}

// NewAnalysisToolsClient constructs a client for the ida.worker.v1.AnalysisTools service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalysisToolsClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalysisToolsClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analysisToolsMethods := v1.File_ida_worker_v1_service_proto.Services().ByName("AnalysisTools").Methods()
	return &analysisToolsClient{
		getBytes: connect.NewClient[v1.GetBytesRequest, v1.GetBytesResponse](
			httpClient,
			baseURL+AnalysisToolsGetBytesProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetBytes")),
			connect.WithClientOptions(opts...),
		),
		getDisasm: connect.NewClient[v1.GetDisasmRequest, v1.GetDisasmResponse](
			httpClient,
			baseURL+AnalysisToolsGetDisasmProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetDisasm")),
			connect.WithClientOptions(opts...),
		),
		getFunctionDisasm: connect.NewClient[v1.GetFunctionDisasmRequest, v1.GetFunctionDisasmResponse](
			httpClient,
			baseURL+AnalysisToolsGetFunctionDisasmProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetFunctionDisasm")),
			connect.WithClientOptions(opts...),
		),
		getDecompiled: connect.NewClient[v1.GetDecompiledRequest, v1.GetDecompiledResponse](
			httpClient,
			baseURL+AnalysisToolsGetDecompiledProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetDecompiled")),
			connect.WithClientOptions(opts...),
		),
		getFunctionName: connect.NewClient[v1.GetFunctionNameRequest, v1.GetFunctionNameResponse](
			httpClient,
			baseURL+AnalysisToolsGetFunctionNameProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetFunctionName")),
			connect.WithClientOptions(opts...),
		),
		getSegments: connect.NewClient[v1.GetSegmentsRequest, v1.GetSegmentsResponse](
			httpClient,
			baseURL+AnalysisToolsGetSegmentsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetSegments")),
			connect.WithClientOptions(opts...),
		),
		getFunctions: connect.NewClient[v1.GetFunctionsRequest, v1.GetFunctionsResponse](
			httpClient,
			baseURL+AnalysisToolsGetFunctionsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetFunctions")),
			connect.WithClientOptions(opts...),
		),
		getXRefsTo: connect.NewClient[v1.GetXRefsToRequest, v1.GetXRefsToResponse](
			httpClient,
			baseURL+AnalysisToolsGetXRefsToProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetXRefsTo")),
			connect.WithClientOptions(opts...),
		),
		getXRefsFrom: connect.NewClient[v1.GetXRefsFromRequest, v1.GetXRefsFromResponse](
			httpClient,
			baseURL+AnalysisToolsGetXRefsFromProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetXRefsFrom")),
			connect.WithClientOptions(opts...),
		),
		getDataRefs: connect.NewClient[v1.GetDataRefsRequest, v1.GetDataRefsResponse](
			httpClient,
			baseURL+AnalysisToolsGetDataRefsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetDataRefs")),
			connect.WithClientOptions(opts...),
		),
		getStringXRefs: connect.NewClient[v1.GetStringXRefsRequest, v1.GetStringXRefsResponse](
			httpClient,
			baseURL+AnalysisToolsGetStringXRefsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetStringXRefs")),
			connect.WithClientOptions(opts...),
		),
		getImports: connect.NewClient[v1.GetImportsRequest, v1.GetImportsResponse](
			httpClient,
			baseURL+AnalysisToolsGetImportsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetImports")),
			connect.WithClientOptions(opts...),
		),
		getExports: connect.NewClient[v1.GetExportsRequest, v1.GetExportsResponse](
			httpClient,
			baseURL+AnalysisToolsGetExportsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetExports")),
			connect.WithClientOptions(opts...),
		),
		getEntryPoint: connect.NewClient[v1.GetEntryPointRequest, v1.GetEntryPointResponse](
			httpClient,
			baseURL+AnalysisToolsGetEntryPointProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetEntryPoint")),
			connect.WithClientOptions(opts...),
		),
		getStrings: connect.NewClient[v1.GetStringsRequest, v1.GetStringsResponse](
			httpClient,
			baseURL+AnalysisToolsGetStringsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetStrings")),
			connect.WithClientOptions(opts...),
		),
		makeFunction: connect.NewClient[v1.MakeFunctionRequest, v1.MakeFunctionResponse](
			httpClient,
			baseURL+AnalysisToolsMakeFunctionProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("MakeFunction")),
			connect.WithClientOptions(opts...),
		),
		importIl2Cpp: connect.NewClient[v1.ImportIl2CppRequest, v1.ImportIl2CppResponse](
			httpClient,
			baseURL+AnalysisToolsImportIl2CppProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("ImportIl2Cpp")),
			connect.WithClientOptions(opts...),
		),
		importFlutter: connect.NewClient[v1.ImportFlutterRequest, v1.ImportFlutterResponse](
			httpClient,
			baseURL+AnalysisToolsImportFlutterProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("ImportFlutter")),
			connect.WithClientOptions(opts...),
		),
		getGlobals: connect.NewClient[v1.GetGlobalsRequest, v1.GetGlobalsResponse](
			httpClient,
			baseURL+AnalysisToolsGetGlobalsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetGlobals")),
			connect.WithClientOptions(opts...),
		),
		setGlobalType: connect.NewClient[v1.SetGlobalTypeRequest, v1.SetGlobalTypeResponse](
			httpClient,
			baseURL+AnalysisToolsSetGlobalTypeProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("SetGlobalType")),
			connect.WithClientOptions(opts...),
		),
		renameGlobal: connect.NewClient[v1.RenameGlobalRequest, v1.RenameGlobalResponse](
			httpClient,
			baseURL+AnalysisToolsRenameGlobalProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("RenameGlobal")),
			connect.WithClientOptions(opts...),
		),
		dataReadString: connect.NewClient[v1.DataReadStringRequest, v1.DataReadStringResponse](
			httpClient,
			baseURL+AnalysisToolsDataReadStringProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("DataReadString")),
			connect.WithClientOptions(opts...),
		),
		dataReadByte: connect.NewClient[v1.DataReadByteRequest, v1.DataReadByteResponse](
			httpClient,
			baseURL+AnalysisToolsDataReadByteProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("DataReadByte")),
			connect.WithClientOptions(opts...),
		),
		findBinary: connect.NewClient[v1.FindBinaryRequest, v1.FindBinaryResponse](
			httpClient,
			baseURL+AnalysisToolsFindBinaryProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("FindBinary")),
			connect.WithClientOptions(opts...),
		),
		findText: connect.NewClient[v1.FindTextRequest, v1.FindTextResponse](
			httpClient,
			baseURL+AnalysisToolsFindTextProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("FindText")),
			connect.WithClientOptions(opts...),
		),
		listStructs: connect.NewClient[v1.ListStructsRequest, v1.ListStructsResponse](
			httpClient,
			baseURL+AnalysisToolsListStructsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("ListStructs")),
			connect.WithClientOptions(opts...),
		),
		getStruct: connect.NewClient[v1.GetStructRequest, v1.GetStructResponse](
			httpClient,
			baseURL+AnalysisToolsGetStructProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetStruct")),
			connect.WithClientOptions(opts...),
		),
		listEnums: connect.NewClient[v1.ListEnumsRequest, v1.ListEnumsResponse](
			httpClient,
			baseURL+AnalysisToolsListEnumsProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("ListEnums")),
			connect.WithClientOptions(opts...),
		),
		getEnum: connect.NewClient[v1.GetEnumRequest, v1.GetEnumResponse](
			httpClient,
			baseURL+AnalysisToolsGetEnumProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetEnum")),
			connect.WithClientOptions(opts...),
		),
		getFunctionInfo: connect.NewClient[v1.GetFunctionInfoRequest, v1.GetFunctionInfoResponse](
			httpClient,
			baseURL+AnalysisToolsGetFunctionInfoProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetFunctionInfo")),
			connect.WithClientOptions(opts...),
		),
		getTypeAt: connect.NewClient[v1.GetTypeAtRequest, v1.GetTypeAtResponse](
			httpClient,
			baseURL+AnalysisToolsGetTypeAtProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetTypeAt")),
			connect.WithClientOptions(opts...),
		),
		getDwordAt: connect.NewClient[v1.GetDwordAtRequest, v1.GetDwordAtResponse](
			httpClient,
			baseURL+AnalysisToolsGetDwordAtProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetDwordAt")),
			connect.WithClientOptions(opts...),
		),
		getQwordAt: connect.NewClient[v1.GetQwordAtRequest, v1.GetQwordAtResponse](
			httpClient,
			baseURL+AnalysisToolsGetQwordAtProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetQwordAt")),
			connect.WithClientOptions(opts...),
		),
		getInstructionLength: connect.NewClient[v1.GetInstructionLengthRequest, v1.GetInstructionLengthResponse](
			httpClient,
			baseURL+AnalysisToolsGetInstructionLengthProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetInstructionLength")),
			connect.WithClientOptions(opts...),
		),
		setComment: connect.NewClient[v1.SetCommentRequest, v1.SetCommentResponse](
			httpClient,
			baseURL+AnalysisToolsSetCommentProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("SetComment")),
			connect.WithClientOptions(opts...),
		),
		getComment: connect.NewClient[v1.GetCommentRequest, v1.GetCommentResponse](
			httpClient,
			baseURL+AnalysisToolsGetCommentProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetComment")),
			connect.WithClientOptions(opts...),
		),
		setFuncComment: connect.NewClient[v1.SetFuncCommentRequest, v1.SetFuncCommentResponse](
			httpClient,
			baseURL+AnalysisToolsSetFuncCommentProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("SetFuncComment")),
			connect.WithClientOptions(opts...),
		),
		getFuncComment: connect.NewClient[v1.GetFuncCommentRequest, v1.GetFuncCommentResponse](
			httpClient,
			baseURL+AnalysisToolsGetFuncCommentProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetFuncComment")),
			connect.WithClientOptions(opts...),
		),
		setLvarType: connect.NewClient[v1.SetLvarTypeRequest, v1.SetLvarTypeResponse](
			httpClient,
			baseURL+AnalysisToolsSetLvarTypeProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("SetLvarType")),
			connect.WithClientOptions(opts...),
		),
		renameLvar: connect.NewClient[v1.RenameLvarRequest, v1.RenameLvarResponse](
			httpClient,
			baseURL+AnalysisToolsRenameLvarProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("RenameLvar")),
			connect.WithClientOptions(opts...),
		),
		setDecompilerComment: connect.NewClient[v1.SetDecompilerCommentRequest, v1.SetDecompilerCommentResponse](
			httpClient,
			baseURL+AnalysisToolsSetDecompilerCommentProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("SetDecompilerComment")),
			connect.WithClientOptions(opts...),
		),
		setName: connect.NewClient[v1.SetNameRequest, v1.SetNameResponse](
			httpClient,
			baseURL+AnalysisToolsSetNameProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("SetName")),
			connect.WithClientOptions(opts...),
		),
		getName: connect.NewClient[v1.GetNameRequest, v1.GetNameResponse](
			httpClient,
			baseURL+AnalysisToolsGetNameProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("GetName")),
			connect.WithClientOptions(opts...),
		),
		deleteName: connect.NewClient[v1.DeleteNameRequest, v1.DeleteNameResponse](
			httpClient,
			baseURL+AnalysisToolsDeleteNameProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("DeleteName")),
			connect.WithClientOptions(opts...),
		),
		setFunctionType: connect.NewClient[v1.SetFunctionTypeRequest, v1.SetFunctionTypeResponse](
			httpClient,
			baseURL+AnalysisToolsSetFunctionTypeProcedure,
			connect.WithSchema(analysisToolsMethods.ByName("SetFunctionType")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analysisToolsClient implements AnalysisToolsClient.
type analysisToolsClient struct {
	getBytes             *connect.Client[v1.GetBytesRequest, v1.GetBytesResponse]
	getDisasm            *connect.Client[v1.GetDisasmRequest, v1.GetDisasmResponse]
	getFunctionDisasm    *connect.Client[v1.GetFunctionDisasmRequest, v1.GetFunctionDisasmResponse]
	getDecompiled        *connect.Client[v1.GetDecompiledRequest, v1.GetDecompiledResponse]
	getFunctionName      *connect.Client[v1.GetFunctionNameRequest, v1.GetFunctionNameResponse]
	getSegments          *connect.Client[v1.GetSegmentsRequest, v1.GetSegmentsResponse]
	getFunctions         *connect.Client[v1.GetFunctionsRequest, v1.GetFunctionsResponse]
	getXRefsTo           *connect.Client[v1.GetXRefsToRequest, v1.GetXRefsToResponse]
	getXRefsFrom         *connect.Client[v1.GetXRefsFromRequest, v1.GetXRefsFromResponse]
	getDataRefs          *connect.Client[v1.GetDataRefsRequest, v1.GetDataRefsResponse]
	getStringXRefs       *connect.Client[v1.GetStringXRefsRequest, v1.GetStringXRefsResponse]
	getImports           *connect.Client[v1.GetImportsRequest, v1.GetImportsResponse]
	getExports           *connect.Client[v1.GetExportsRequest, v1.GetExportsResponse]
	getEntryPoint        *connect.Client[v1.GetEntryPointRequest, v1.GetEntryPointResponse]
	getStrings           *connect.Client[v1.GetStringsRequest, v1.GetStringsResponse]
	makeFunction         *connect.Client[v1.MakeFunctionRequest, v1.MakeFunctionResponse]
	importIl2Cpp         *connect.Client[v1.ImportIl2CppRequest, v1.ImportIl2CppResponse]
	importFlutter        *connect.Client[v1.ImportFlutterRequest, v1.ImportFlutterResponse]
	getGlobals           *connect.Client[v1.GetGlobalsRequest, v1.GetGlobalsResponse]
	setGlobalType        *connect.Client[v1.SetGlobalTypeRequest, v1.SetGlobalTypeResponse]
	renameGlobal         *connect.Client[v1.RenameGlobalRequest, v1.RenameGlobalResponse]
	dataReadString       *connect.Client[v1.DataReadStringRequest, v1.DataReadStringResponse]
	dataReadByte         *connect.Client[v1.DataReadByteRequest, v1.DataReadByteResponse]
	findBinary           *connect.Client[v1.FindBinaryRequest, v1.FindBinaryResponse]
	findText             *connect.Client[v1.FindTextRequest, v1.FindTextResponse]
	listStructs          *connect.Client[v1.ListStructsRequest, v1.ListStructsResponse]
	getStruct            *connect.Client[v1.GetStructRequest, v1.GetStructResponse]
	listEnums            *connect.Client[v1.ListEnumsRequest, v1.ListEnumsResponse]
	getEnum              *connect.Client[v1.GetEnumRequest, v1.GetEnumResponse]
	getFunctionInfo      *connect.Client[v1.GetFunctionInfoRequest, v1.GetFunctionInfoResponse]
	getTypeAt            *connect.Client[v1.GetTypeAtRequest, v1.GetTypeAtResponse]
	getDwordAt           *connect.Client[v1.GetDwordAtRequest, v1.GetDwordAtResponse]
	getQwordAt           *connect.Client[v1.GetQwordAtRequest, v1.GetQwordAtResponse]
	getInstructionLength *connect.Client[v1.GetInstructionLengthRequest, v1.GetInstructionLengthResponse]
	setComment           *connect.Client[v1.SetCommentRequest, v1.SetCommentResponse]
	getComment           *connect.Client[v1.GetCommentRequest, v1.GetCommentResponse]
	setFuncComment       *connect.Client[v1.SetFuncCommentRequest, v1.SetFuncCommentResponse]
	getFuncComment       *connect.Client[v1.GetFuncCommentRequest, v1.GetFuncCommentResponse]
	setLvarType          *connect.Client[v1.SetLvarTypeRequest, v1.SetLvarTypeResponse]
	renameLvar           *connect.Client[v1.RenameLvarRequest, v1.RenameLvarResponse]
	setDecompilerComment *connect.Client[v1.SetDecompilerCommentRequest, v1.SetDecompilerCommentResponse]
	setName              *connect.Client[v1.SetNameRequest, v1.SetNameResponse]
	getName              *connect.Client[v1.GetNameRequest, v1.GetNameResponse]
	deleteName           *connect.Client[v1.DeleteNameRequest, v1.DeleteNameResponse]
	setFunctionType      *connect.Client[v1.SetFunctionTypeRequest, v1.SetFunctionTypeResponse]
}

// GetBytes calls ida.worker.v1.AnalysisTools.GetBytes.
func (c *analysisToolsClient) GetBytes(ctx context.Context, req *connect.Request[v1.GetBytesRequest]) (*connect.Response[v1.GetBytesResponse], error) {
	return c.getBytes.CallUnary(ctx, req)
}

// GetDisasm calls ida.worker.v1.AnalysisTools.GetDisasm.
func (c *analysisToolsClient) GetDisasm(ctx context.Context, req *connect.Request[v1.GetDisasmRequest]) (*connect.Response[v1.GetDisasmResponse], error) {
	return c.getDisasm.CallUnary(ctx, req)
}

// GetFunctionDisasm calls ida.worker.v1.AnalysisTools.GetFunctionDisasm.
func (c *analysisToolsClient) GetFunctionDisasm(ctx context.Context, req *connect.Request[v1.GetFunctionDisasmRequest]) (*connect.Response[v1.GetFunctionDisasmResponse], error) {
	return c.getFunctionDisasm.CallUnary(ctx, req)
}

// GetDecompiled calls ida.worker.v1.AnalysisTools.GetDecompiled.
func (c *analysisToolsClient) GetDecompiled(ctx context.Context, req *connect.Request[v1.GetDecompiledRequest]) (*connect.Response[v1.GetDecompiledResponse], error) {
	return c.getDecompiled.CallUnary(ctx, req)
}

// GetFunctionName calls ida.worker.v1.AnalysisTools.GetFunctionName.
func (c *analysisToolsClient) GetFunctionName(ctx context.Context, req *connect.Request[v1.GetFunctionNameRequest]) (*connect.Response[v1.GetFunctionNameResponse], error) {
	return c.getFunctionName.CallUnary(ctx, req)
}

// GetSegments calls ida.worker.v1.AnalysisTools.GetSegments.
func (c *analysisToolsClient) GetSegments(ctx context.Context, req *connect.Request[v1.GetSegmentsRequest]) (*connect.Response[v1.GetSegmentsResponse], error) {
	return c.getSegments.CallUnary(ctx, req)
}

// GetFunctions calls ida.worker.v1.AnalysisTools.GetFunctions.
func (c *analysisToolsClient) GetFunctions(ctx context.Context, req *connect.Request[v1.GetFunctionsRequest]) (*connect.Response[v1.GetFunctionsResponse], error) {
	return c.getFunctions.CallUnary(ctx, req)
}

// GetXRefsTo calls ida.worker.v1.AnalysisTools.GetXRefsTo.
func (c *analysisToolsClient) GetXRefsTo(ctx context.Context, req *connect.Request[v1.GetXRefsToRequest]) (*connect.Response[v1.GetXRefsToResponse], error) {
	return c.getXRefsTo.CallUnary(ctx, req)
}

// GetXRefsFrom calls ida.worker.v1.AnalysisTools.GetXRefsFrom.
func (c *analysisToolsClient) GetXRefsFrom(ctx context.Context, req *connect.Request[v1.GetXRefsFromRequest]) (*connect.Response[v1.GetXRefsFromResponse], error) {
	return c.getXRefsFrom.CallUnary(ctx, req)
}

// GetDataRefs calls ida.worker.v1.AnalysisTools.GetDataRefs.
func (c *analysisToolsClient) GetDataRefs(ctx context.Context, req *connect.Request[v1.GetDataRefsRequest]) (*connect.Response[v1.GetDataRefsResponse], error) {
	return c.getDataRefs.CallUnary(ctx, req)
}

// GetStringXRefs calls ida.worker.v1.AnalysisTools.GetStringXRefs.
func (c *analysisToolsClient) GetStringXRefs(ctx context.Context, req *connect.Request[v1.GetStringXRefsRequest]) (*connect.Response[v1.GetStringXRefsResponse], error) {
	return c.getStringXRefs.CallUnary(ctx, req)
}

// GetImports calls ida.worker.v1.AnalysisTools.GetImports.
func (c *analysisToolsClient) GetImports(ctx context.Context, req *connect.Request[v1.GetImportsRequest]) (*connect.Response[v1.GetImportsResponse], error) {
	return c.getImports.CallUnary(ctx, req)
}

// GetExports calls ida.worker.v1.AnalysisTools.GetExports.
func (c *analysisToolsClient) GetExports(ctx context.Context, req *connect.Request[v1.GetExportsRequest]) (*connect.Response[v1.GetExportsResponse], error) {
	return c.getExports.CallUnary(ctx, req)
}

// GetEntryPoint calls ida.worker.v1.AnalysisTools.GetEntryPoint.
func (c *analysisToolsClient) GetEntryPoint(ctx context.Context, req *connect.Request[v1.GetEntryPointRequest]) (*connect.Response[v1.GetEntryPointResponse], error) {
	return c.getEntryPoint.CallUnary(ctx, req)
}

// GetStrings calls ida.worker.v1.AnalysisTools.GetStrings.
func (c *analysisToolsClient) GetStrings(ctx context.Context, req *connect.Request[v1.GetStringsRequest]) (*connect.Response[v1.GetStringsResponse], error) {
	return c.getStrings.CallUnary(ctx, req)
}

// MakeFunction calls ida.worker.v1.AnalysisTools.MakeFunction.
func (c *analysisToolsClient) MakeFunction(ctx context.Context, req *connect.Request[v1.MakeFunctionRequest]) (*connect.Response[v1.MakeFunctionResponse], error) {
	return c.makeFunction.CallUnary(ctx, req)
}

// ImportIl2Cpp calls ida.worker.v1.AnalysisTools.ImportIl2Cpp.
func (c *analysisToolsClient) ImportIl2Cpp(ctx context.Context, req *connect.Request[v1.ImportIl2CppRequest]) (*connect.Response[v1.ImportIl2CppResponse], error) {
	return c.importIl2Cpp.CallUnary(ctx, req)
}

// ImportFlutter calls ida.worker.v1.AnalysisTools.ImportFlutter.
func (c *analysisToolsClient) ImportFlutter(ctx context.Context, req *connect.Request[v1.ImportFlutterRequest]) (*connect.Response[v1.ImportFlutterResponse], error) {
	return c.importFlutter.CallUnary(ctx, req)
}

// GetGlobals calls ida.worker.v1.AnalysisTools.GetGlobals.
func (c *analysisToolsClient) GetGlobals(ctx context.Context, req *connect.Request[v1.GetGlobalsRequest]) (*connect.Response[v1.GetGlobalsResponse], error) {
	return c.getGlobals.CallUnary(ctx, req)
}

// SetGlobalType calls ida.worker.v1.AnalysisTools.SetGlobalType.
func (c *analysisToolsClient) SetGlobalType(ctx context.Context, req *connect.Request[v1.SetGlobalTypeRequest]) (*connect.Response[v1.SetGlobalTypeResponse], error) {
	return c.setGlobalType.CallUnary(ctx, req)
}

// RenameGlobal calls ida.worker.v1.AnalysisTools.RenameGlobal.
func (c *analysisToolsClient) RenameGlobal(ctx context.Context, req *connect.Request[v1.RenameGlobalRequest]) (*connect.Response[v1.RenameGlobalResponse], error) {
	return c.renameGlobal.CallUnary(ctx, req)
}

// DataReadString calls ida.worker.v1.AnalysisTools.DataReadString.
func (c *analysisToolsClient) DataReadString(ctx context.Context, req *connect.Request[v1.DataReadStringRequest]) (*connect.Response[v1.DataReadStringResponse], error) {
	return c.dataReadString.CallUnary(ctx, req)
}

// DataReadByte calls ida.worker.v1.AnalysisTools.DataReadByte.
func (c *analysisToolsClient) DataReadByte(ctx context.Context, req *connect.Request[v1.DataReadByteRequest]) (*connect.Response[v1.DataReadByteResponse], error) {
	return c.dataReadByte.CallUnary(ctx, req)
}

// FindBinary calls ida.worker.v1.AnalysisTools.FindBinary.
func (c *analysisToolsClient) FindBinary(ctx context.Context, req *connect.Request[v1.FindBinaryRequest]) (*connect.Response[v1.FindBinaryResponse], error) {
	return c.findBinary.CallUnary(ctx, req)
}

// FindText calls ida.worker.v1.AnalysisTools.FindText.
func (c *analysisToolsClient) FindText(ctx context.Context, req *connect.Request[v1.FindTextRequest]) (*connect.Response[v1.FindTextResponse], error) {
	return c.findText.CallUnary(ctx, req)
}

// ListStructs calls ida.worker.v1.AnalysisTools.ListStructs.
func (c *analysisToolsClient) ListStructs(ctx context.Context, req *connect.Request[v1.ListStructsRequest]) (*connect.Response[v1.ListStructsResponse], error) {
	return c.listStructs.CallUnary(ctx, req)
}

// GetStruct calls ida.worker.v1.AnalysisTools.GetStruct.
func (c *analysisToolsClient) GetStruct(ctx context.Context, req *connect.Request[v1.GetStructRequest]) (*connect.Response[v1.GetStructResponse], error) {
	return c.getStruct.CallUnary(ctx, req)
}

// ListEnums calls ida.worker.v1.AnalysisTools.ListEnums.
func (c *analysisToolsClient) ListEnums(ctx context.Context, req *connect.Request[v1.ListEnumsRequest]) (*connect.Response[v1.ListEnumsResponse], error) {
	return c.listEnums.CallUnary(ctx, req)
}

// GetEnum calls ida.worker.v1.AnalysisTools.GetEnum.
func (c *analysisToolsClient) GetEnum(ctx context.Context, req *connect.Request[v1.GetEnumRequest]) (*connect.Response[v1.GetEnumResponse], error) {
	return c.getEnum.CallUnary(ctx, req)
}

// GetFunctionInfo calls ida.worker.v1.AnalysisTools.GetFunctionInfo.
func (c *analysisToolsClient) GetFunctionInfo(ctx context.Context, req *connect.Request[v1.GetFunctionInfoRequest]) (*connect.Response[v1.GetFunctionInfoResponse], error) {
	return c.getFunctionInfo.CallUnary(ctx, req)
}

// GetTypeAt calls ida.worker.v1.AnalysisTools.GetTypeAt.
func (c *analysisToolsClient) GetTypeAt(ctx context.Context, req *connect.Request[v1.GetTypeAtRequest]) (*connect.Response[v1.GetTypeAtResponse], error) {
	return c.getTypeAt.CallUnary(ctx, req)
}

// GetDwordAt calls ida.worker.v1.AnalysisTools.GetDwordAt.
func (c *analysisToolsClient) GetDwordAt(ctx context.Context, req *connect.Request[v1.GetDwordAtRequest]) (*connect.Response[v1.GetDwordAtResponse], error) {
	return c.getDwordAt.CallUnary(ctx, req)
}

// GetQwordAt calls ida.worker.v1.AnalysisTools.GetQwordAt.
func (c *analysisToolsClient) GetQwordAt(ctx context.Context, req *connect.Request[v1.GetQwordAtRequest]) (*connect.Response[v1.GetQwordAtResponse], error) {
	return c.getQwordAt.CallUnary(ctx, req)
}

// GetInstructionLength calls ida.worker.v1.AnalysisTools.GetInstructionLength.
func (c *analysisToolsClient) GetInstructionLength(ctx context.Context, req *connect.Request[v1.GetInstructionLengthRequest]) (*connect.Response[v1.GetInstructionLengthResponse], error) {
	return c.getInstructionLength.CallUnary(ctx, req)
}

// SetComment calls ida.worker.v1.AnalysisTools.SetComment.
func (c *analysisToolsClient) SetComment(ctx context.Context, req *connect.Request[v1.SetCommentRequest]) (*connect.Response[v1.SetCommentResponse], error) {
	return c.setComment.CallUnary(ctx, req)
}

// GetComment calls ida.worker.v1.AnalysisTools.GetComment.
func (c *analysisToolsClient) GetComment(ctx context.Context, req *connect.Request[v1.GetCommentRequest]) (*connect.Response[v1.GetCommentResponse], error) {
	return c.getComment.CallUnary(ctx, req)
}

// SetFuncComment calls ida.worker.v1.AnalysisTools.SetFuncComment.
func (c *analysisToolsClient) SetFuncComment(ctx context.Context, req *connect.Request[v1.SetFuncCommentRequest]) (*connect.Response[v1.SetFuncCommentResponse], error) {
	return c.setFuncComment.CallUnary(ctx, req)
}

// GetFuncComment calls ida.worker.v1.AnalysisTools.GetFuncComment.
func (c *analysisToolsClient) GetFuncComment(ctx context.Context, req *connect.Request[v1.GetFuncCommentRequest]) (*connect.Response[v1.GetFuncCommentResponse], error) {
	return c.getFuncComment.CallUnary(ctx, req)
}

// SetLvarType calls ida.worker.v1.AnalysisTools.SetLvarType.
func (c *analysisToolsClient) SetLvarType(ctx context.Context, req *connect.Request[v1.SetLvarTypeRequest]) (*connect.Response[v1.SetLvarTypeResponse], error) {
	return c.setLvarType.CallUnary(ctx, req)
}

// RenameLvar calls ida.worker.v1.AnalysisTools.RenameLvar.
func (c *analysisToolsClient) RenameLvar(ctx context.Context, req *connect.Request[v1.RenameLvarRequest]) (*connect.Response[v1.RenameLvarResponse], error) {
	return c.renameLvar.CallUnary(ctx, req)
}

// SetDecompilerComment calls ida.worker.v1.AnalysisTools.SetDecompilerComment.
func (c *analysisToolsClient) SetDecompilerComment(ctx context.Context, req *connect.Request[v1.SetDecompilerCommentRequest]) (*connect.Response[v1.SetDecompilerCommentResponse], error) {
	return c.setDecompilerComment.CallUnary(ctx, req)
}

// SetName calls ida.worker.v1.AnalysisTools.SetName.
func (c *analysisToolsClient) SetName(ctx context.Context, req *connect.Request[v1.SetNameRequest]) (*connect.Response[v1.SetNameResponse], error) {
	return c.setName.CallUnary(ctx, req)
}

// GetName calls ida.worker.v1.AnalysisTools.GetName.
func (c *analysisToolsClient) GetName(ctx context.Context, req *connect.Request[v1.GetNameRequest]) (*connect.Response[v1.GetNameResponse], error) {
	return c.getName.CallUnary(ctx, req)
}

// DeleteName calls ida.worker.v1.AnalysisTools.DeleteName.
func (c *analysisToolsClient) DeleteName(ctx context.Context, req *connect.Request[v1.DeleteNameRequest]) (*connect.Response[v1.DeleteNameResponse], error) {
	return c.deleteName.CallUnary(ctx, req)
}

// SetFunctionType calls ida.worker.v1.AnalysisTools.SetFunctionType.
func (c *analysisToolsClient) SetFunctionType(ctx context.Context, req *connect.Request[v1.SetFunctionTypeRequest]) (*connect.Response[v1.SetFunctionTypeResponse], error) {
	return c.setFunctionType.CallUnary(ctx, req)
}

// AnalysisToolsHandler is an implementation of the ida.worker.v1.AnalysisTools service.
type AnalysisToolsHandler interface {
	// GetBytes reads raw bytes from address
	GetBytes(context.Context, *connect.Request[v1.GetBytesRequest]) (*connect.Response[v1.GetBytesResponse], error)
	// GetDisasm returns disassembly at address
	GetDisasm(context.Context, *connect.Request[v1.GetDisasmRequest]) (*connect.Response[v1.GetDisasmResponse], error)
	// GetFunctionDisasm returns full disassembly for a function
	GetFunctionDisasm(context.Context, *connect.Request[v1.GetFunctionDisasmRequest]) (*connect.Response[v1.GetFunctionDisasmResponse], error)
	// GetDecompiled returns decompiled pseudocode
	GetDecompiled(context.Context, *connect.Request[v1.GetDecompiledRequest]) (*connect.Response[v1.GetDecompiledResponse], error)
	// GetFunctionName returns function name at address
	GetFunctionName(context.Context, *connect.Request[v1.GetFunctionNameRequest]) (*connect.Response[v1.GetFunctionNameResponse], error)
	// GetSegments returns all memory segments
	GetSegments(context.Context, *connect.Request[v1.GetSegmentsRequest]) (*connect.Response[v1.GetSegmentsResponse], error)
	// GetFunctions returns all functions
	GetFunctions(context.Context, *connect.Request[v1.GetFunctionsRequest]) (*connect.Response[v1.GetFunctionsResponse], error)
	// GetXRefsTo returns cross-references to address
	GetXRefsTo(context.Context, *connect.Request[v1.GetXRefsToRequest]) (*connect.Response[v1.GetXRefsToResponse], error)
	// GetXRefsFrom returns outgoing references from address
	GetXRefsFrom(context.Context, *connect.Request[v1.GetXRefsFromRequest]) (*connect.Response[v1.GetXRefsFromResponse], error)
	// GetDataRefs returns data references to address
	GetDataRefs(context.Context, *connect.Request[v1.GetDataRefsRequest]) (*connect.Response[v1.GetDataRefsResponse], error)
	// GetStringXRefs returns string references for address
	GetStringXRefs(context.Context, *connect.Request[v1.GetStringXRefsRequest]) (*connect.Response[v1.GetStringXRefsResponse], error)
	// GetImports returns import table
	GetImports(context.Context, *connect.Request[v1.GetImportsRequest]) (*connect.Response[v1.GetImportsResponse], error)
	// GetExports returns export table
	GetExports(context.Context, *connect.Request[v1.GetExportsRequest]) (*connect.Response[v1.GetExportsResponse], error)
	// GetEntryPoint returns binary entry point
	GetEntryPoint(context.Context, *connect.Request[v1.GetEntryPointRequest]) (*connect.Response[v1.GetEntryPointResponse], error)
	// GetStrings returns all strings in binary
	GetStrings(context.Context, *connect.Request[v1.GetStringsRequest]) (*connect.Response[v1.GetStringsResponse], error)
	// MakeFunction creates function at address
	MakeFunction(context.Context, *connect.Request[v1.MakeFunctionRequest]) (*connect.Response[v1.MakeFunctionResponse], error)
	// ImportIl2Cpp ingests Il2CppDumper metadata into the current database
	ImportIl2Cpp(context.Context, *connect.Request[v1.ImportIl2CppRequest]) (*connect.Response[v1.ImportIl2CppResponse], error)
	// ImportFlutter ingests Blutter output into the current database
	ImportFlutter(context.Context, *connect.Request[v1.ImportFlutterRequest]) (*connect.Response[v1.ImportFlutterResponse], error)
	// GetGlobals enumerates global variables
	GetGlobals(context.Context, *connect.Request[v1.GetGlobalsRequest]) (*connect.Response[v1.GetGlobalsResponse], error)
	// SetGlobalType sets the type of a global variable
	SetGlobalType(context.Context, *connect.Request[v1.SetGlobalTypeRequest]) (*connect.Response[v1.SetGlobalTypeResponse], error)
	// RenameGlobal renames a global variable
	RenameGlobal(context.Context, *connect.Request[v1.RenameGlobalRequest]) (*connect.Response[v1.RenameGlobalResponse], error)
	// DataReadString reads an ASCII/UTF-8 string from memory
	DataReadString(context.Context, *connect.Request[v1.DataReadStringRequest]) (*connect.Response[v1.DataReadStringResponse], error)
	// DataReadByte reads a single byte from memory
	DataReadByte(context.Context, *connect.Request[v1.DataReadByteRequest]) (*connect.Response[v1.DataReadByteResponse], error)
	// FindBinary searches for byte patterns
	FindBinary(context.Context, *connect.Request[v1.FindBinaryRequest]) (*connect.Response[v1.FindBinaryResponse], error)
	// FindText searches for ASCII/UTF-8 strings
	FindText(context.Context, *connect.Request[v1.FindTextRequest]) (*connect.Response[v1.FindTextResponse], error)
	// ListStructs enumerates structure definitions
	ListStructs(context.Context, *connect.Request[v1.ListStructsRequest]) (*connect.Response[v1.ListStructsResponse], error)
	// GetStruct returns metadata for a specific structure
	GetStruct(context.Context, *connect.Request[v1.GetStructRequest]) (*connect.Response[v1.GetStructResponse], error)
	// ListEnums enumerates all enumerations with optional filtering
	ListEnums(context.Context, *connect.Request[v1.ListEnumsRequest]) (*connect.Response[v1.ListEnumsResponse], error)
	// GetEnum returns metadata for a specific enumeration
	GetEnum(context.Context, *connect.Request[v1.GetEnumRequest]) (*connect.Response[v1.GetEnumResponse], error)
	// GetFunctionInfo returns comprehensive function metadata
	GetFunctionInfo(context.Context, *connect.Request[v1.GetFunctionInfoRequest]) (*connect.Response[v1.GetFunctionInfoResponse], error)
	// GetTypeAt returns type information at address
	GetTypeAt(context.Context, *connect.Request[v1.GetTypeAtRequest]) (*connect.Response[v1.GetTypeAtResponse], error)
	// GetDwordAt reads 32-bit value
	GetDwordAt(context.Context, *connect.Request[v1.GetDwordAtRequest]) (*connect.Response[v1.GetDwordAtResponse], error)
	// GetQwordAt reads 64-bit value
	GetQwordAt(context.Context, *connect.Request[v1.GetQwordAtRequest]) (*connect.Response[v1.GetQwordAtResponse], error)
	// GetInstructionLength returns instruction size
	GetInstructionLength(context.Context, *connect.Request[v1.GetInstructionLengthRequest]) (*connect.Response[v1.GetInstructionLengthResponse], error)
	// SetComment sets comment at address
	SetComment(context.Context, *connect.Request[v1.SetCommentRequest]) (*connect.Response[v1.SetCommentResponse], error)
	// GetComment returns comment at address
	GetComment(context.Context, *connect.Request[v1.GetCommentRequest]) (*connect.Response[v1.GetCommentResponse], error)
	// SetFuncComment sets function comment
	SetFuncComment(context.Context, *connect.Request[v1.SetFuncCommentRequest]) (*connect.Response[v1.SetFuncCommentResponse], error)
	// GetFuncComment returns function comment
	GetFuncComment(context.Context, *connect.Request[v1.GetFuncCommentRequest]) (*connect.Response[v1.GetFuncCommentResponse], error)
	// SetLvarType sets Hex-Rays local variable type
	SetLvarType(context.Context, *connect.Request[v1.SetLvarTypeRequest]) (*connect.Response[v1.SetLvarTypeResponse], error)
	// RenameLvar renames a Hex-Rays local variable
	RenameLvar(context.Context, *connect.Request[v1.RenameLvarRequest]) (*connect.Response[v1.RenameLvarResponse], error)
	// SetDecompilerComment sets a Hex-Rays pseudocode comment
	SetDecompilerComment(context.Context, *connect.Request[v1.SetDecompilerCommentRequest]) (*connect.Response[v1.SetDecompilerCommentResponse], error)
	// SetName sets name at address
	SetName(context.Context, *connect.Request[v1.SetNameRequest]) (*connect.Response[v1.SetNameResponse], error)
	// GetName returns name at address
	GetName(context.Context, *connect.Request[v1.GetNameRequest]) (*connect.Response[v1.GetNameResponse], error)
	// DeleteName removes name at address
	DeleteName(context.Context, *connect.Request[v1.DeleteNameRequest]) (*connect.Response[v1.DeleteNameResponse], error)
	// SetFunctionType applies a C-style prototype to a function
	SetFunctionType(context.Context, *connect.Request[v1.SetFunctionTypeRequest]) (*connect.Response[v1.SetFunctionTypeResponse], error)
}

// NewAnalysisToolsHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalysisToolsHandler(svc AnalysisToolsHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analysisToolsMethods := v1.File_ida_worker_v1_service_proto.Services().ByName("AnalysisTools").Methods()
	analysisToolsGetBytesHandler := connect.NewUnaryHandler(
		AnalysisToolsGetBytesProcedure,
		svc.GetBytes,
		connect.WithSchema(analysisToolsMethods.ByName("GetBytes")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetDisasmHandler := connect.NewUnaryHandler(
		AnalysisToolsGetDisasmProcedure,
		svc.GetDisasm,
		connect.WithSchema(analysisToolsMethods.ByName("GetDisasm")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetFunctionDisasmHandler := connect.NewUnaryHandler(
		AnalysisToolsGetFunctionDisasmProcedure,
		svc.GetFunctionDisasm,
		connect.WithSchema(analysisToolsMethods.ByName("GetFunctionDisasm")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetDecompiledHandler := connect.NewUnaryHandler(
		AnalysisToolsGetDecompiledProcedure,
		svc.GetDecompiled,
		connect.WithSchema(analysisToolsMethods.ByName("GetDecompiled")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetFunctionNameHandler := connect.NewUnaryHandler(
		AnalysisToolsGetFunctionNameProcedure,
		svc.GetFunctionName,
		connect.WithSchema(analysisToolsMethods.ByName("GetFunctionName")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetSegmentsHandler := connect.NewUnaryHandler(
		AnalysisToolsGetSegmentsProcedure,
		svc.GetSegments,
		connect.WithSchema(analysisToolsMethods.ByName("GetSegments")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetFunctionsHandler := connect.NewUnaryHandler(
		AnalysisToolsGetFunctionsProcedure,
		svc.GetFunctions,
		connect.WithSchema(analysisToolsMethods.ByName("GetFunctions")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetXRefsToHandler := connect.NewUnaryHandler(
		AnalysisToolsGetXRefsToProcedure,
		svc.GetXRefsTo,
		connect.WithSchema(analysisToolsMethods.ByName("GetXRefsTo")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetXRefsFromHandler := connect.NewUnaryHandler(
		AnalysisToolsGetXRefsFromProcedure,
		svc.GetXRefsFrom,
		connect.WithSchema(analysisToolsMethods.ByName("GetXRefsFrom")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetDataRefsHandler := connect.NewUnaryHandler(
		AnalysisToolsGetDataRefsProcedure,
		svc.GetDataRefs,
		connect.WithSchema(analysisToolsMethods.ByName("GetDataRefs")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetStringXRefsHandler := connect.NewUnaryHandler(
		AnalysisToolsGetStringXRefsProcedure,
		svc.GetStringXRefs,
		connect.WithSchema(analysisToolsMethods.ByName("GetStringXRefs")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetImportsHandler := connect.NewUnaryHandler(
		AnalysisToolsGetImportsProcedure,
		svc.GetImports,
		connect.WithSchema(analysisToolsMethods.ByName("GetImports")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetExportsHandler := connect.NewUnaryHandler(
		AnalysisToolsGetExportsProcedure,
		svc.GetExports,
		connect.WithSchema(analysisToolsMethods.ByName("GetExports")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetEntryPointHandler := connect.NewUnaryHandler(
		AnalysisToolsGetEntryPointProcedure,
		svc.GetEntryPoint,
		connect.WithSchema(analysisToolsMethods.ByName("GetEntryPoint")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetStringsHandler := connect.NewUnaryHandler(
		AnalysisToolsGetStringsProcedure,
		svc.GetStrings,
		connect.WithSchema(analysisToolsMethods.ByName("GetStrings")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsMakeFunctionHandler := connect.NewUnaryHandler(
		AnalysisToolsMakeFunctionProcedure,
		svc.MakeFunction,
		connect.WithSchema(analysisToolsMethods.ByName("MakeFunction")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsImportIl2CppHandler := connect.NewUnaryHandler(
		AnalysisToolsImportIl2CppProcedure,
		svc.ImportIl2Cpp,
		connect.WithSchema(analysisToolsMethods.ByName("ImportIl2Cpp")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsImportFlutterHandler := connect.NewUnaryHandler(
		AnalysisToolsImportFlutterProcedure,
		svc.ImportFlutter,
		connect.WithSchema(analysisToolsMethods.ByName("ImportFlutter")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetGlobalsHandler := connect.NewUnaryHandler(
		AnalysisToolsGetGlobalsProcedure,
		svc.GetGlobals,
		connect.WithSchema(analysisToolsMethods.ByName("GetGlobals")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsSetGlobalTypeHandler := connect.NewUnaryHandler(
		AnalysisToolsSetGlobalTypeProcedure,
		svc.SetGlobalType,
		connect.WithSchema(analysisToolsMethods.ByName("SetGlobalType")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsRenameGlobalHandler := connect.NewUnaryHandler(
		AnalysisToolsRenameGlobalProcedure,
		svc.RenameGlobal,
		connect.WithSchema(analysisToolsMethods.ByName("RenameGlobal")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsDataReadStringHandler := connect.NewUnaryHandler(
		AnalysisToolsDataReadStringProcedure,
		svc.DataReadString,
		connect.WithSchema(analysisToolsMethods.ByName("DataReadString")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsDataReadByteHandler := connect.NewUnaryHandler(
		AnalysisToolsDataReadByteProcedure,
		svc.DataReadByte,
		connect.WithSchema(analysisToolsMethods.ByName("DataReadByte")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsFindBinaryHandler := connect.NewUnaryHandler(
		AnalysisToolsFindBinaryProcedure,
		svc.FindBinary,
		connect.WithSchema(analysisToolsMethods.ByName("FindBinary")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsFindTextHandler := connect.NewUnaryHandler(
		AnalysisToolsFindTextProcedure,
		svc.FindText,
		connect.WithSchema(analysisToolsMethods.ByName("FindText")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsListStructsHandler := connect.NewUnaryHandler(
		AnalysisToolsListStructsProcedure,
		svc.ListStructs,
		connect.WithSchema(analysisToolsMethods.ByName("ListStructs")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetStructHandler := connect.NewUnaryHandler(
		AnalysisToolsGetStructProcedure,
		svc.GetStruct,
		connect.WithSchema(analysisToolsMethods.ByName("GetStruct")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsListEnumsHandler := connect.NewUnaryHandler(
		AnalysisToolsListEnumsProcedure,
		svc.ListEnums,
		connect.WithSchema(analysisToolsMethods.ByName("ListEnums")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetEnumHandler := connect.NewUnaryHandler(
		AnalysisToolsGetEnumProcedure,
		svc.GetEnum,
		connect.WithSchema(analysisToolsMethods.ByName("GetEnum")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetFunctionInfoHandler := connect.NewUnaryHandler(
		AnalysisToolsGetFunctionInfoProcedure,
		svc.GetFunctionInfo,
		connect.WithSchema(analysisToolsMethods.ByName("GetFunctionInfo")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetTypeAtHandler := connect.NewUnaryHandler(
		AnalysisToolsGetTypeAtProcedure,
		svc.GetTypeAt,
		connect.WithSchema(analysisToolsMethods.ByName("GetTypeAt")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetDwordAtHandler := connect.NewUnaryHandler(
		AnalysisToolsGetDwordAtProcedure,
		svc.GetDwordAt,
		connect.WithSchema(analysisToolsMethods.ByName("GetDwordAt")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetQwordAtHandler := connect.NewUnaryHandler(
		AnalysisToolsGetQwordAtProcedure,
		svc.GetQwordAt,
		connect.WithSchema(analysisToolsMethods.ByName("GetQwordAt")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetInstructionLengthHandler := connect.NewUnaryHandler(
		AnalysisToolsGetInstructionLengthProcedure,
		svc.GetInstructionLength,
		connect.WithSchema(analysisToolsMethods.ByName("GetInstructionLength")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsSetCommentHandler := connect.NewUnaryHandler(
		AnalysisToolsSetCommentProcedure,
		svc.SetComment,
		connect.WithSchema(analysisToolsMethods.ByName("SetComment")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetCommentHandler := connect.NewUnaryHandler(
		AnalysisToolsGetCommentProcedure,
		svc.GetComment,
		connect.WithSchema(analysisToolsMethods.ByName("GetComment")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsSetFuncCommentHandler := connect.NewUnaryHandler(
		AnalysisToolsSetFuncCommentProcedure,
		svc.SetFuncComment,
		connect.WithSchema(analysisToolsMethods.ByName("SetFuncComment")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetFuncCommentHandler := connect.NewUnaryHandler(
		AnalysisToolsGetFuncCommentProcedure,
		svc.GetFuncComment,
		connect.WithSchema(analysisToolsMethods.ByName("GetFuncComment")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsSetLvarTypeHandler := connect.NewUnaryHandler(
		AnalysisToolsSetLvarTypeProcedure,
		svc.SetLvarType,
		connect.WithSchema(analysisToolsMethods.ByName("SetLvarType")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsRenameLvarHandler := connect.NewUnaryHandler(
		AnalysisToolsRenameLvarProcedure,
		svc.RenameLvar,
		connect.WithSchema(analysisToolsMethods.ByName("RenameLvar")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsSetDecompilerCommentHandler := connect.NewUnaryHandler(
		AnalysisToolsSetDecompilerCommentProcedure,
		svc.SetDecompilerComment,
		connect.WithSchema(analysisToolsMethods.ByName("SetDecompilerComment")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsSetNameHandler := connect.NewUnaryHandler(
		AnalysisToolsSetNameProcedure,
		svc.SetName,
		connect.WithSchema(analysisToolsMethods.ByName("SetName")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsGetNameHandler := connect.NewUnaryHandler(
		AnalysisToolsGetNameProcedure,
		svc.GetName,
		connect.WithSchema(analysisToolsMethods.ByName("GetName")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsDeleteNameHandler := connect.NewUnaryHandler(
		AnalysisToolsDeleteNameProcedure,
		svc.DeleteName,
		connect.WithSchema(analysisToolsMethods.ByName("DeleteName")),
		connect.WithHandlerOptions(opts...),
	)
	analysisToolsSetFunctionTypeHandler := connect.NewUnaryHandler(
		AnalysisToolsSetFunctionTypeProcedure,
		svc.SetFunctionType,
		connect.WithSchema(analysisToolsMethods.ByName("SetFunctionType")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ida.worker.v1.AnalysisTools/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalysisToolsGetBytesProcedure:
			analysisToolsGetBytesHandler.ServeHTTP(w, r)
		case AnalysisToolsGetDisasmProcedure:
			analysisToolsGetDisasmHandler.ServeHTTP(w, r)
		case AnalysisToolsGetFunctionDisasmProcedure:
			analysisToolsGetFunctionDisasmHandler.ServeHTTP(w, r)
		case AnalysisToolsGetDecompiledProcedure:
			analysisToolsGetDecompiledHandler.ServeHTTP(w, r)
		case AnalysisToolsGetFunctionNameProcedure:
			analysisToolsGetFunctionNameHandler.ServeHTTP(w, r)
		case AnalysisToolsGetSegmentsProcedure:
			analysisToolsGetSegmentsHandler.ServeHTTP(w, r)
		case AnalysisToolsGetFunctionsProcedure:
			analysisToolsGetFunctionsHandler.ServeHTTP(w, r)
		case AnalysisToolsGetXRefsToProcedure:
			analysisToolsGetXRefsToHandler.ServeHTTP(w, r)
		case AnalysisToolsGetXRefsFromProcedure:
			analysisToolsGetXRefsFromHandler.ServeHTTP(w, r)
		case AnalysisToolsGetDataRefsProcedure:
			analysisToolsGetDataRefsHandler.ServeHTTP(w, r)
		case AnalysisToolsGetStringXRefsProcedure:
			analysisToolsGetStringXRefsHandler.ServeHTTP(w, r)
		case AnalysisToolsGetImportsProcedure:
			analysisToolsGetImportsHandler.ServeHTTP(w, r)
		case AnalysisToolsGetExportsProcedure:
			analysisToolsGetExportsHandler.ServeHTTP(w, r)
		case AnalysisToolsGetEntryPointProcedure:
			analysisToolsGetEntryPointHandler.ServeHTTP(w, r)
		case AnalysisToolsGetStringsProcedure:
			analysisToolsGetStringsHandler.ServeHTTP(w, r)
		case AnalysisToolsMakeFunctionProcedure:
			analysisToolsMakeFunctionHandler.ServeHTTP(w, r)
		case AnalysisToolsImportIl2CppProcedure:
			analysisToolsImportIl2CppHandler.ServeHTTP(w, r)
		case AnalysisToolsImportFlutterProcedure:
			analysisToolsImportFlutterHandler.ServeHTTP(w, r)
		case AnalysisToolsGetGlobalsProcedure:
			analysisToolsGetGlobalsHandler.ServeHTTP(w, r)
		case AnalysisToolsSetGlobalTypeProcedure:
			analysisToolsSetGlobalTypeHandler.ServeHTTP(w, r)
		case AnalysisToolsRenameGlobalProcedure:
			analysisToolsRenameGlobalHandler.ServeHTTP(w, r)
		case AnalysisToolsDataReadStringProcedure:
			analysisToolsDataReadStringHandler.ServeHTTP(w, r)
		case AnalysisToolsDataReadByteProcedure:
			analysisToolsDataReadByteHandler.ServeHTTP(w, r)
		case AnalysisToolsFindBinaryProcedure:
			analysisToolsFindBinaryHandler.ServeHTTP(w, r)
		case AnalysisToolsFindTextProcedure:
			analysisToolsFindTextHandler.ServeHTTP(w, r)
		case AnalysisToolsListStructsProcedure:
			analysisToolsListStructsHandler.ServeHTTP(w, r)
		case AnalysisToolsGetStructProcedure:
			analysisToolsGetStructHandler.ServeHTTP(w, r)
		case AnalysisToolsListEnumsProcedure:
			analysisToolsListEnumsHandler.ServeHTTP(w, r)
		case AnalysisToolsGetEnumProcedure:
			analysisToolsGetEnumHandler.ServeHTTP(w, r)
		case AnalysisToolsGetFunctionInfoProcedure:
			analysisToolsGetFunctionInfoHandler.ServeHTTP(w, r)
		case AnalysisToolsGetTypeAtProcedure:
			analysisToolsGetTypeAtHandler.ServeHTTP(w, r)
		case AnalysisToolsGetDwordAtProcedure:
			analysisToolsGetDwordAtHandler.ServeHTTP(w, r)
		case AnalysisToolsGetQwordAtProcedure:
			analysisToolsGetQwordAtHandler.ServeHTTP(w, r)
		case AnalysisToolsGetInstructionLengthProcedure:
			analysisToolsGetInstructionLengthHandler.ServeHTTP(w, r)
		case AnalysisToolsSetCommentProcedure:
			analysisToolsSetCommentHandler.ServeHTTP(w, r)
		case AnalysisToolsGetCommentProcedure:
			analysisToolsGetCommentHandler.ServeHTTP(w, r)
		case AnalysisToolsSetFuncCommentProcedure:
			analysisToolsSetFuncCommentHandler.ServeHTTP(w, r)
		case AnalysisToolsGetFuncCommentProcedure:
			analysisToolsGetFuncCommentHandler.ServeHTTP(w, r)
		case AnalysisToolsSetLvarTypeProcedure:
			analysisToolsSetLvarTypeHandler.ServeHTTP(w, r)
		case AnalysisToolsRenameLvarProcedure:
			analysisToolsRenameLvarHandler.ServeHTTP(w, r)
		case AnalysisToolsSetDecompilerCommentProcedure:
			analysisToolsSetDecompilerCommentHandler.ServeHTTP(w, r)
		case AnalysisToolsSetNameProcedure:
			analysisToolsSetNameHandler.ServeHTTP(w, r)
		case AnalysisToolsGetNameProcedure:
			analysisToolsGetNameHandler.ServeHTTP(w, r)
		case AnalysisToolsDeleteNameProcedure:
			analysisToolsDeleteNameHandler.ServeHTTP(w, r)
		case AnalysisToolsSetFunctionTypeProcedure:
			analysisToolsSetFunctionTypeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalysisToolsHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalysisToolsHandler struct{}

func (UnimplementedAnalysisToolsHandler) GetBytes(context.Context, *connect.Request[v1.GetBytesRequest]) (*connect.Response[v1.GetBytesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetBytes is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetDisasm(context.Context, *connect.Request[v1.GetDisasmRequest]) (*connect.Response[v1.GetDisasmResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetDisasm is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetFunctionDisasm(context.Context, *connect.Request[v1.GetFunctionDisasmRequest]) (*connect.Response[v1.GetFunctionDisasmResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetFunctionDisasm is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetDecompiled(context.Context, *connect.Request[v1.GetDecompiledRequest]) (*connect.Response[v1.GetDecompiledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetDecompiled is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetFunctionName(context.Context, *connect.Request[v1.GetFunctionNameRequest]) (*connect.Response[v1.GetFunctionNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetFunctionName is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetSegments(context.Context, *connect.Request[v1.GetSegmentsRequest]) (*connect.Response[v1.GetSegmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetSegments is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetFunctions(context.Context, *connect.Request[v1.GetFunctionsRequest]) (*connect.Response[v1.GetFunctionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetFunctions is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetXRefsTo(context.Context, *connect.Request[v1.GetXRefsToRequest]) (*connect.Response[v1.GetXRefsToResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetXRefsTo is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetXRefsFrom(context.Context, *connect.Request[v1.GetXRefsFromRequest]) (*connect.Response[v1.GetXRefsFromResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetXRefsFrom is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetDataRefs(context.Context, *connect.Request[v1.GetDataRefsRequest]) (*connect.Response[v1.GetDataRefsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetDataRefs is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetStringXRefs(context.Context, *connect.Request[v1.GetStringXRefsRequest]) (*connect.Response[v1.GetStringXRefsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetStringXRefs is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetImports(context.Context, *connect.Request[v1.GetImportsRequest]) (*connect.Response[v1.GetImportsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetImports is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetExports(context.Context, *connect.Request[v1.GetExportsRequest]) (*connect.Response[v1.GetExportsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetExports is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetEntryPoint(context.Context, *connect.Request[v1.GetEntryPointRequest]) (*connect.Response[v1.GetEntryPointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetEntryPoint is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetStrings(context.Context, *connect.Request[v1.GetStringsRequest]) (*connect.Response[v1.GetStringsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetStrings is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) MakeFunction(context.Context, *connect.Request[v1.MakeFunctionRequest]) (*connect.Response[v1.MakeFunctionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.MakeFunction is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) ImportIl2Cpp(context.Context, *connect.Request[v1.ImportIl2CppRequest]) (*connect.Response[v1.ImportIl2CppResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.ImportIl2Cpp is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) ImportFlutter(context.Context, *connect.Request[v1.ImportFlutterRequest]) (*connect.Response[v1.ImportFlutterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.ImportFlutter is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetGlobals(context.Context, *connect.Request[v1.GetGlobalsRequest]) (*connect.Response[v1.GetGlobalsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetGlobals is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) SetGlobalType(context.Context, *connect.Request[v1.SetGlobalTypeRequest]) (*connect.Response[v1.SetGlobalTypeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.SetGlobalType is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) RenameGlobal(context.Context, *connect.Request[v1.RenameGlobalRequest]) (*connect.Response[v1.RenameGlobalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.RenameGlobal is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) DataReadString(context.Context, *connect.Request[v1.DataReadStringRequest]) (*connect.Response[v1.DataReadStringResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.DataReadString is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) DataReadByte(context.Context, *connect.Request[v1.DataReadByteRequest]) (*connect.Response[v1.DataReadByteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.DataReadByte is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) FindBinary(context.Context, *connect.Request[v1.FindBinaryRequest]) (*connect.Response[v1.FindBinaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.FindBinary is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) FindText(context.Context, *connect.Request[v1.FindTextRequest]) (*connect.Response[v1.FindTextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.FindText is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) ListStructs(context.Context, *connect.Request[v1.ListStructsRequest]) (*connect.Response[v1.ListStructsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.ListStructs is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetStruct(context.Context, *connect.Request[v1.GetStructRequest]) (*connect.Response[v1.GetStructResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetStruct is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) ListEnums(context.Context, *connect.Request[v1.ListEnumsRequest]) (*connect.Response[v1.ListEnumsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.ListEnums is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetEnum(context.Context, *connect.Request[v1.GetEnumRequest]) (*connect.Response[v1.GetEnumResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetEnum is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetFunctionInfo(context.Context, *connect.Request[v1.GetFunctionInfoRequest]) (*connect.Response[v1.GetFunctionInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetFunctionInfo is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetTypeAt(context.Context, *connect.Request[v1.GetTypeAtRequest]) (*connect.Response[v1.GetTypeAtResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetTypeAt is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetDwordAt(context.Context, *connect.Request[v1.GetDwordAtRequest]) (*connect.Response[v1.GetDwordAtResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetDwordAt is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetQwordAt(context.Context, *connect.Request[v1.GetQwordAtRequest]) (*connect.Response[v1.GetQwordAtResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetQwordAt is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetInstructionLength(context.Context, *connect.Request[v1.GetInstructionLengthRequest]) (*connect.Response[v1.GetInstructionLengthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetInstructionLength is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) SetComment(context.Context, *connect.Request[v1.SetCommentRequest]) (*connect.Response[v1.SetCommentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.SetComment is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetComment(context.Context, *connect.Request[v1.GetCommentRequest]) (*connect.Response[v1.GetCommentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetComment is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) SetFuncComment(context.Context, *connect.Request[v1.SetFuncCommentRequest]) (*connect.Response[v1.SetFuncCommentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.SetFuncComment is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetFuncComment(context.Context, *connect.Request[v1.GetFuncCommentRequest]) (*connect.Response[v1.GetFuncCommentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetFuncComment is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) SetLvarType(context.Context, *connect.Request[v1.SetLvarTypeRequest]) (*connect.Response[v1.SetLvarTypeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.SetLvarType is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) RenameLvar(context.Context, *connect.Request[v1.RenameLvarRequest]) (*connect.Response[v1.RenameLvarResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.RenameLvar is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) SetDecompilerComment(context.Context, *connect.Request[v1.SetDecompilerCommentRequest]) (*connect.Response[v1.SetDecompilerCommentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.SetDecompilerComment is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) SetName(context.Context, *connect.Request[v1.SetNameRequest]) (*connect.Response[v1.SetNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.SetName is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) GetName(context.Context, *connect.Request[v1.GetNameRequest]) (*connect.Response[v1.GetNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.GetName is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) DeleteName(context.Context, *connect.Request[v1.DeleteNameRequest]) (*connect.Response[v1.DeleteNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.DeleteName is not implemented"))
}

func (UnimplementedAnalysisToolsHandler) SetFunctionType(context.Context, *connect.Request[v1.SetFunctionTypeRequest]) (*connect.Response[v1.SetFunctionTypeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.AnalysisTools.SetFunctionType is not implemented"))
}

// HealthcheckClient is a client for the ida.worker.v1.Healthcheck service.
type HealthcheckClient interface {
	// Ping simple liveness check
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	// StatusStream streams worker metrics
	StatusStream(context.Context, *connect.Request[v1.StatusStreamRequest]) (*connect.ServerStreamForClient[v1.WorkerStatus], error)
}

// NewHealthcheckClient constructs a client for the ida.worker.v1.Healthcheck service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthcheckClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthcheckClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthcheckMethods := v1.File_ida_worker_v1_service_proto.Services().ByName("Healthcheck").Methods()
	return &healthcheckClient{
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+HealthcheckPingProcedure,
			connect.WithSchema(healthcheckMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		statusStream: connect.NewClient[v1.StatusStreamRequest, v1.WorkerStatus](
			httpClient,
			baseURL+HealthcheckStatusStreamProcedure,
			connect.WithSchema(healthcheckMethods.ByName("StatusStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthcheckClient implements HealthcheckClient.
type healthcheckClient struct {
	ping         *connect.Client[v1.PingRequest, v1.PingResponse]
	statusStream *connect.Client[v1.StatusStreamRequest, v1.WorkerStatus]
}

// Ping calls ida.worker.v1.Healthcheck.Ping.
func (c *healthcheckClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// StatusStream calls ida.worker.v1.Healthcheck.StatusStream.
func (c *healthcheckClient) StatusStream(ctx context.Context, req *connect.Request[v1.StatusStreamRequest]) (*connect.ServerStreamForClient[v1.WorkerStatus], error) {
	return c.statusStream.CallServerStream(ctx, req)
}

// HealthcheckHandler is an implementation of the ida.worker.v1.Healthcheck service.
type HealthcheckHandler interface {
	// Ping simple liveness check
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	// StatusStream streams worker metrics
	StatusStream(context.Context, *connect.Request[v1.StatusStreamRequest], *connect.ServerStream[v1.WorkerStatus]) error
}

// NewHealthcheckHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthcheckHandler(svc HealthcheckHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthcheckMethods := v1.File_ida_worker_v1_service_proto.Services().ByName("Healthcheck").Methods()
	healthcheckPingHandler := connect.NewUnaryHandler(
		HealthcheckPingProcedure,
		svc.Ping,
		connect.WithSchema(healthcheckMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	healthcheckStatusStreamHandler := connect.NewServerStreamHandler(
		HealthcheckStatusStreamProcedure,
		svc.StatusStream,
		connect.WithSchema(healthcheckMethods.ByName("StatusStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ida.worker.v1.Healthcheck/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthcheckPingProcedure:
			healthcheckPingHandler.ServeHTTP(w, r)
		case HealthcheckStatusStreamProcedure:
			healthcheckStatusStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthcheckHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthcheckHandler struct{}

func (UnimplementedHealthcheckHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.Healthcheck.Ping is not implemented"))
}

func (UnimplementedHealthcheckHandler) StatusStream(context.Context, *connect.Request[v1.StatusStreamRequest], *connect.ServerStream[v1.WorkerStatus]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ida.worker.v1.Healthcheck.StatusStream is not implemented"))
}
